### ISSUE TITLE
'react-native-step-counter@*' is not in this registry.

### ISSUE THREAD

**Issue by Pardeep7** [AndrewDongminYoo/react-native-step-counter#48]
When i install this package then it show below error
npm WARN using --force Recommended protections disabled.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-native-step-counter - Not found
npm ERR! 404 
npm ERR! 404  'react-native-step-counter@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in: /Users/apple/.npm/_logs/2024-04-22T06_58_11_308Z-debug-0.log

**Comment by bendspoons** [comment]
@Pardeep7 Use npm i @dongminyu/react-native-step-counter instead

**Comment by AndrewDongminYoo** [comment]
I wanted to use the name react-native-step-counter, but when I tried to npm publish it, I was told it wasn't allowed because there was an existing library with a similar name and it could be confusing. I feel like it added to the confusion. I don't like the package name either because it's too long, but you can try installing it as @dongminyu/react-native-step-counter.
